project_id            = "chrome-flight-435809-p8"
region                = "us-central1"
zone                  = "us-central1-a"
cluster_name          = "dev-gke-cluster"
argocd_chart_version  = "8.2.5"
appsets_chart_version = "0.1.4"
